CREATE PROCEDURE [dbo].[RecreateIndexes] (@tableName VARCHAR(255))
AS
/* 
-- Joshua Granville 10/09/2015
-- Recreate indexes on passed table
-- The proc will query tmp_indexes a table that contains all indexes
-- Table generated by EXEC dbo.[BackupIndexes]

USE:
	EXEC [RecreateIndexes] '_PersonReference'

OUTPUT:
	CREATE NONCLUSTERED INDEX [IX__PersonReference] ON _PersonReference (personID)
	CREATE NONCLUSTERED INDEX [IX__PersonReference_1] ON _PersonReference (externalID)
	CREATE NONCLUSTERED INDEX [IX__PersonReference_2] ON _PersonReference (migrateGUID)
	CREATE NONCLUSTERED INDEX [IX__PersonReference_3] ON _PersonReference (referencePersonID)
	CREATE NONCLUSTERED INDEX [IX__PersonReference_4] ON _PersonReference (clientCorporationID)
	CREATE NONCLUSTERED INDEX [IX__PersonReference_5] ON _PersonReference (jobPostingID)
*/
SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED


--Recreate indexes
--Don't judge my cursor, this is a practical use.
DECLARE @v_create VARCHAR(255)

DECLARE csr_create cursor FOR
SELECT DISTINCT createStatement FROM dbo.tmp_indexes
Where tableName = @tableName

OPEN csr_create
FETCH NEXT FROM csr_create into @v_create;

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @v_create;
	EXECUTE(@v_create);
	FETCH NEXT FROM csr_create into @v_create;
END
CLOSE csr_create;
DEALLOCATE csr_create;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SET NOCOUNT OFF


GO